[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "speed: marks tests as a speed test (deselect with '-m \"not speed\"')",
]
